[package]
name = "async-block-send"
version = "0.1.0"
authors = ["Hexilee <i@hexilee.me>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
